### ISSUE TITLE
需要設置免運標題

### ISSUE THREAD

**Issue by bem8867** [ECPay/WooCommerce_Logistics#10]
可以設定"免運標題"嗎? 例如：超商取貨：0
買家才知道運費已經免費，謝謝。

![default](https://user-images.githubusercontent.com/38309827/38659774-7aba1f26-3e5d-11e8-9de8-ef93fb138a54.PNG)
![default](https://user-images.githubusercontent.com/38309827/38659935-17623f2a-3e5e-11e8-8d23-56f907097b07.PNG)

**Comment by AllennChang** [comment]
您好, 這個部份, 我會反應給我們的開發團隊評估

**Comment by robert1112** [comment]
需要，請問資訊有更新嗎？謝謝～

**Comment by AllennChang** [comment]
您好. 功能改善的部份, 改反應給開發團隊囉, 但時程要依開發團隊安排, 若造成您的困擾, 深感抱歉

**Comment by AllennChang** [comment]
@bem8867  @robert1112  
 WooCommerce 新版已增加類似功能, 為避免造成相容性問題, 模組的部份不會提供此功能, 若造成您的困擾, 深感抱歉
