### ISSUE TITLE
後台建立物流訂單是否僅限超商取貨(付款)? 

### ISSUE THREAD

**Issue by virtualuke** [ECPay/WooCommerce_Logistics#13]
後台建立物流訂單功能是否僅限超商取貨(付款)的訂單? 若為宅配訂單無法串接建立黑貓or 宅配通的物流訂單?

**Comment by AllennChang** [comment]
後台建立物流訂單功能是否僅限超商取貨(付款)的訂單? 

=>是的

若為宅配訂單無法串接建立黑貓or 宅配通的物流訂單?

=>目前woocommerce尚未支援此功能，

若您急需此功能，建議貴司資訊人員，

可以參考我們的API文件，

https://www.ecpay.com.tw/Service/API_Dwnld ，

來調整設計您的需求，謝謝。

**Comment by Eisekson** [comment]
請問現在宅配訂單有支援woocommerce 建立黑貓或宅配通的物流訂單嗎？
