### ISSUE TITLE
物流單收件人姓名順序

### ISSUE THREAD

**Issue by anki630** [ECPay/WooCommerce_Logistics#14]
請問是否可以修正物流單收件人姓名順序。
ECPay-shipping-integration.php:                    'ReceiverName'         => $orderInfo['_billing_first_name'][0] . $orderInfo['_billing_last_name'][0],
依台灣地區的使用習慣應改為
ECPay-shipping-integration.php:                    'ReceiverName'         => $orderInfo['_billing_last_name'][0]  . $orderInfo['_billing_first_name'][0],
才合理。

**Comment by AllennChang** [comment]
感謝你的提醒, 已將您的問題反應給開發團隊,預計將排入改善功能項目中, 再次感謝您
