### ISSUE TITLE
客戶收件人名稱太長，無法建立物流訂單

### ISSUE THREAD

**Issue by anki630** [ECPay/WooCommerce_Logistics#15]
客戶名稱為：Wang Frannie
建立物流訂單的按鈕不會出現，只會出現：ReceiverName max length is 10.
![2018-08-03 1 44 46](https://user-images.githubusercontent.com/7203595/43626201-761ded34-9723-11e8-94e2-f077c78da3cb.png)

**Comment by AllennChang** [comment]
因為目前超商只接受10個字元的收貨人長度,  所以看是否請客人用中文或英文簡稱, 例如, W.Frannie

**Comment by AllennChang** [comment]
以下為API文件欄位的說明
*ReceiverName   收件人姓名  String    (10) |
注意事項:    
 1.       字元限制為為4~10字元(中文2~5個字,    英文4~10個字)    
2.       不可有符號^ ' ` ! ＠ # % & * +    \ " < > \| _ [ ] 。    
3.          不可有空白 , 及，若帶有空白, 及，系統自動去除。
-- | -- | -- | --

**Comment by thebobthebob** [comment]
Hello,我也遇到一樣的問題,但我測試用的名字只有三個字
`<blockquote class="imgur-embed-pub" lang="en" data-id="a/aFqMEDe" data-context="false" ><a href="//imgur.com/a/aFqMEDe"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>`

**Comment by AllennChang** [comment]
您好, 感謝您的發問, 請試試在姓名欄位移除email資訊, 避免造成姓名欄位長度過長,  若有任何問題,歡迎再跟我們反應, 感謝
