### ISSUE TITLE
請問是否支援 wordpress、WooCommerce 新版本？

### ISSUE THREAD

**Issue by kimisme9386** [ECPay/WooCommerce_Logistics#16]
* wordpress 4.9.x
* WooCommerce 3.4.x

請問是否支援呢？

**Comment by AllennChang** [comment]
您好, 感謝你的發問, 目前我們未測試過WooCommerce 3.4.x的版本, 目前已測試過的版本只支援到, WooCommerce 3.2.1 ,若未來有完成最新版程式, 我們會再更新到官網及GITHUB上的說明

**Comment by kimisme9386** [comment]
了解，謝謝你的回覆，看來當初買版型的時候，應該先確認這件事情> <"，昏.....
