### ISSUE TITLE
物流選取超商取貨付款，再選店家。付款方式還是出現其它付款方式沒有超商取貨付款。

### ISSUE THREAD

**Issue by anki630** [ECPay/WooCommerce_Logistics#18]
WooCommerce_Logistics版本: V1.2.180829
Woocommerce版本：3.5.1
例如：
1. 物流選取超商取貨付款-->選取統一超商寄貨便取貨付款--->選項變成"統一超商寄貨便取貨付款"
2. 再選電子地圖-->原本所選取的"統一超商寄貨便取貨付款"變成預設選項"--------"
3. 下方的取貨門市會帶出剛選的資料。
綠界科技超商取貨	
門市名稱: xxx門市
門市地址: 範例地址…
門市電話: 9999999
使用綠界科技超商取貨，連絡電話請填寫手機號碼。
4. 付款方式還是出現其它付款方式(綠界ATM、信用卡付款)，但就是沒有超商取貨付款。

**Comment by AllennChang** [comment]
您好, 我們目前模組只支援到Woocommerce版本：3.2.x 的版本, 尚未支援Woocommerce版本： 3.5.1  ,

**Comment by anki630** [comment]
好的，期待更新。

-- 
Chihao Lin

On November 15, 2018 at 8:54:36 AM, Chang Allen (notifications@github.com)
wrote:

您好, 我們目前模組只支援到Woocommerce版本：3.2.x 的版本, 尚未支援Woocommerce版本： 3.5.1 ,

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ECPay/WooCommerce_Logistics/issues/18#issuecomment-438875147>,
or mute the thread

**Comment by seanlee1205** [comment]
請問有更新的計畫嗎? 目前大多的template和plugin都已經到3.6版了，但確被這個模組卡在3.4.6

**Comment by AllennChang** [comment]
> 請問有更新的計畫嗎? 目前大多的template和plugin都已經到3.6版了，但確被這個模組卡在3.4.6
您好, 感謝您的反應,  目前我們已有安排更新的開發計劃,待完成後會更新在這裡

**Comment by AllennChang** [comment]
您好, 目前我們版本已更新到 3.6.4,若有任何問題, 歡迎再跟我們反應, 感謝
