### ISSUE TITLE
重選超商店鋪後不會記錄更新的買家資訊

### ISSUE THREAD

**Issue by din1030** [ECPay/WooCommerce_Logistics#2]
https://github.com/ECPay/WooCommerce_Logistics/blob/90b24652cc4871e10e82d5c1dda1151e1c4cd802/Source/ECPay-shipping-integration.php#L751

目前只有切換不同超商時才會送出 getSession 的 request 記錄 user 更新的資料（姓名、公司、電話、mail）
但若不切換超商，單純重新點選新的店鋪，從電子地圖切回來後，更新的資料就被清空了
應該要在點選電子地圖按鈕的時候也送出 getSession 的 request

<pre>
document.getElementById("__paymentButton").onclick = function() {
    if (document.getElementById('shipping_option').value == "------") {
        alert('請選擇物流方式');
        return false;
    } else {
        // .....
        // getSession ajax call
        // .....
    }                           
    document.getElementById("ECPayForm").submit();
};
</pre>

**Comment by AllennChang** [comment]
你好， 感謝你的提問，為了更有效的處理， 煩請將你的問題,反應到綠界技術客服信箱: techsupport@ecpay.com.tw ，我們將有專人為你服務, 感謝
