### ISSUE TITLE
'@' 字元錯誤，導致中文字誤判

### ISSUE THREAD

**Issue by kimisme9386** [ECPay/WooCommerce_Logistics#20]
https://github.com/ECPay/WooCommerce_Logistics/blob/7fc072eb169f35d56604afda013bb029a0032957/Source/ECPay.Logistics.Integration.php#L2041

https://github.com/ECPay/WooCommerce_Logistics/blob/7fc072eb169f35d56604afda013bb029a0032957/Source/ECPay.Logistics.Integration.php#L2062

https://github.com/ECPay/WooCommerce_Logistics/blob/7fc072eb169f35d56604afda013bb029a0032957/Source/ECPay.Logistics.Integration.php#L2083

## 概述

程式中正規表示法中的 '＠' 字元，非一般我們打的 '@' 字元，會造成中文字如 `堂` 這個字的誤判，導致收件者無法使用這個中文字

**Comment by AllennChang** [comment]
您好, 這個問題我們已經更新, 謝謝您的反應,
