### ISSUE TITLE
請教，超取貨到付該如何排除運送類別

### ISSUE THREAD

**Issue by brian1318** [ECPay/WooCommerce_Logistics#21]
HI Sir：
如題，若我有個產品因材積大無法適用超取貨到付，我該如何將此類宅配型商品排除在超商取貨付款呢？也就是說此類宅配商品在結帳時，是不會超商取貨付款的方式。盼回覆！謝謝

**Comment by AllennChang** [comment]
您好, 感謝您的反應,
目前綠界物流模組尚無法依據材積大小排除運送類別的功能，
若有此部分需求，請參考Woocommerce官方技術文件和綠界PHP SDK範例，
並請您的資訊單位或委外廠商協助開發。
