### ISSUE TITLE
無法超取付款

### ISSUE THREAD

**Issue by aasssddd** [ECPay/WooCommerce_Logistics#22]
wordpress版本: 5.2.3
woocommerce版本: 3.7.0
ECPay Logistics for WooCommerce: 1.3.190807
WooCommerce ECPay Payment: 1.1.180925

選擇超取付款，並選定門市後結帳
系統顯示"請選擇付款方式"後停留在結帳畫面
無法完成交易

**Comment by AllennChang** [comment]
您好, 感謝您的反應, 經我們測試在我們提供模組未發現有相同的情況, 為了進一步了解發生原因, 煩請您寫信到techsupport@ecpay.com.tw 信箱, 會有專員為您服務協助 感謝
