### ISSUE TITLE
物流選取超商取貨付款，付款方式卻還有信用卡、ATM等付款方式

### ISSUE THREAD

**Issue by fsmytsai** [ECPay/WooCommerce_Logistics#24]
在結帳畫面運送方式選超商取貨後，綠界科技超商取貨預設顯示"------"，付款方式預設顯示貨到付款、綠界科技，當綠界科技超商取貨改為"全家取貨付款"後，付款方式卻沒有即時更新，仍然顯示綠界科技的付款方式(刷卡、ATM)，需重新整理頁面後，綠界科技付款方式才會消失。
[示意圖](https://i.imgur.com/L6uLfG8.png)

**Comment by AllennChang** [comment]
您好, 感謝您的反應, 我們會立即回報開發團隊

**Comment by AllennChang** [comment]
您好, 為了加速了解您的問題, 煩請您協助把您問題mail到我們服務信箱, techsupport@ecpay.com.tw
將會由專人進行協助,感謝您

**Comment by fsmytsai** [comment]
已寄信至服務信箱
