### ISSUE TITLE
選完電子超商後，又選擇其他運送方式，付款方式還是只有超商取貨付款

### ISSUE THREAD

**Issue by ChuyuHsu** [ECPay/WooCommerce_Logistics#3]
流程是這樣

1. 選擇運送方式 `綠界超商取貨`
2. 選擇 7-11超商取貨付款
3. 跳轉選擇店家
4. 跳回，付款方式只剩 `超商取貨付款`
5. 改變運送方式回其他，如`宅配`
=> 付款方式還是只剩 `超商取貨付款`
而沒有出現應出現的綠界金流

**Comment by AllennChang** [comment]
你好， 感謝你的提問，為了更有效的處理， 煩請將你的問題,反應到綠界技術客服信箱: techsupport@ecpay.com.tw ，我們將有專人為你服務, 感謝
