### ISSUE TITLE
getSession.php 找不到錯誤

### ISSUE THREAD

**Issue by cty222** [ECPay/WooCommerce_Logistics#8]
ECPay-shipping-integration.php裡面有一個ajax方法
 var ecpay_checkout_request = {
              ajaxUrl: '<?php echo Plugin_URL . '/ecpay_shipping/getSession.php'; ?>',
     checkoutData: <?php echo json_encode($checkout); ?>
 };
去找ecpay_shipping

但是plugins資料夾不是這個名稱
所以找不到

**Comment by AllennChang** [comment]
這個問題解決囉，請下載新的版本更新，感謝您
